name: iPXE Build
on:
  push:
    branches:
      - main

jobs:
  build-ipxe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v29
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build iPXE
        env:
          GITHUB_TOKEN: ${{ secrets.Token }}
        run: (cd binary/; MAKEFLAGS=-j$(nproc) ./script/build_and_pr.sh)
